## Oppgave 1 

En bedrift har variable kostnader gitt av VC $(\mathrm{Q})=20 \cdot \mathrm{Q}+50 \cdot \mathrm{Q}^{0.8}$ kroner, der $\mathrm{Q}$ er mengden som produseres. De faste kostnadene er på 1500000 kroner per periode. Bedriften produserer 10000 enheter per periode.

Hvor stor andel av totalkostnaden er de faste kostnadene ved det produserte volumet?

In [3]:
import numpy as np
import sympy as sp

Q = sp.symbols('Q')

VC = 20*Q + 50*Q**0.8
FC = 1500000
q = 10000
Andel_FC = FC/(VC.subs(Q,q)+FC)

print(f"{Andel_FC:.2f}")

0.84


## Oppgave 2

Etterspørselen til en monopolbedrift er gitt av P(Q)=200-3Q der P er prisen og Q er mengden.

Hva er priselastisiteten ved mengden som maksimerer inntektene?

Gå ut fra definisjon av egenpriselastisitet som gir ikke-negative tall for normal etterspørsel.

---

Price elasticity of demand at any point is calculated using the formula:

$$
E_p ({\varepsilon})  = \left( \frac{dQ}{dP} \right) \times \left( \frac{P}{Q} \right)
$$

---

The connection with total revenue (TR) and marginal revenue (MR) comes when considering revenue maximization. Price elasticity of demand is crucial in determining the behavior of total revenue as price changes, especially since:

- When $|E_p ({\varepsilon}) | > 1$, demand is elastic, and a decrease in price leads to an increase in total revenue.
- When $|E_p ({\varepsilon}) | < 1$, demand is inelastic, and a decrease in price leads to a decrease in total revenue.
- When $|E_p ({\varepsilon}) | = 1$, demand is unit elastic, and total revenue is maximized.

---

$$
MR(Q)=P(Q)\left(1-\frac{1}{\varepsilon}\right)=0 \Leftrightarrow \varepsilon=1
$$

$$ 
MR(Q) = \frac{d(TR)}{dQ}
$$

---

Priselastisiteten ved mengden som maksimerer inntektene? **1**

---

## Oppgave 3

Et selskaps likviditetsgrad 1 oppfyller tommelfingerregelen, mens likviditetsgrad 2 ikke gjør det.

$$
\text{Tommelfingerregler:}
$$
$$
\text{likviditetsgrad 1(Current Ratio) > 2}
$$
$$
\text{likviditetsgrad 2(Quick Ratio) > 1}
$$

For å øke likviditeten vurderer de å ta et kortsiktig lån. Hva vil dette resultere i?

a) En økning av likviditetsgrad 1 og en reduksjon av likviditetsgrad 2.

b) En reduksjon av likviditetsgrad 1 og en Økning av likviditetsgrad 2.

**c) En reduksjon av både likviditetsgrad 1 og likviditetsgrad 2.**

d) En økning av både likviditetsgrad 1 og likviditetsgrad 2.

---

1. **Liquidity Ratios**: These ratios measure a company's ability to meet its short-term obligations with its short-term assets. The two common liquidity ratios mentioned here are:

    - **Likviditetsgrad 1 (Current Ratio)**: This measures a company's ability to cover its short-term liabilities with its short-term assets. It is calculated as:
     $\text{Current Ratio (Likviditetsgrad 1)} = \frac{\text{Current Assets}}{\text{Current Liabilities}}$
     The "thumb rule" often suggests that a healthy current ratio is above 2, meaning the company has twice as many current assets as it has current liabilities.

    - **Likviditetsgrad 2 (Quick Ratio or Acid-Test Ratio)**: This is a more stringent measure than the current ratio because it excludes inventory from current assets. It is calculated as:
     $ \text{Quick Ratio (Likviditetsgrad 2)} = \frac{\text{Current Assets} - \text{Inventory}}{\text{Current Liabilities}} $
     A common rule of thumb for the quick ratio is above 1, indicating that the company can meet its immediate liabilities without selling inventory.

---

**Likviditetsgrad 1:** Likviditetsgrad 1 forteller noe om forholdet mellom omløpsmidler og kortsiktig gjeld. Med andre ord måler det bedriftens evne til å dekke sine betalingsforpliktelser etter hvert som disse forfaller.\
Formelen for $\text{Likviditetsgrad 1} = \frac{\text{Omløpsmidler}}{\text{Kortsiktig gjeld}}$. Likviditetsgrad 1 bør være større enn 2. Omløpsmidler inkluderer Varelager, fordringer, investeringer og kontantbeholdning.

**Likviditetsgrad 2:** Likviditetsgrad 2 måler, som likviditetsgrad 1 forholdet mellom omløpsmidler og kortsiktig gjeld. Forskjellen her er at varelageret, som regnes som de minst likvide omløpsmidlene, er trukket fra.\
Formelen for $\text{Likviditetsgrad 2} = \frac{\text{Omløpsmidler - Varelager}}{\text{Kortsiktig gjeld}}$

---

$$\text{Likviditetsgrad 1} = \frac{\text{Omløpsmidler}}{\text{Kortsiktig gjeld}}$$
$$\text{Likviditetsgrad 2} = \frac{\text{Omløpsmidler - Varelager}}{\text{Kortsiktig gjeld}}$$

## Oppgave 4

Selskapet "Bing \& Bong" har fire produkter i sortimentet A, B, C og D. Prognostisert salgsvolum (stykk), pris (kr/stykk) og direkte kostnader per stykk (kr/stykk) det siste året for de fire produktene er gitt i tabellen:

| Produkt | A | B | C | D |
| :--- | :---: | :---: | :---: | :---: |
| Salgsvolum (stykk) | 8000 | 8000 | 10000 | 10000 |
| Salgspris (kr/stykk) | 10000 | 11000 | 8000 | 9000 |
| Direkte material (kr/stykk) | 1600 | 1700 | 1200 | 1400 |
| Direkte lønn (kr/stykk) | 1500 | 1800 | 1200 | 1500 |
| Øvrige direkte tilvirkningskostnader <br> (kr/stykk) | 200 | 100 | 100 | 200 |
| Salgsprovisjon (kr/stykk) | 1000 | 1100 | 800 | 900 |

Tilleggssatser indirekte kostnader basert på prognosen er

- Indirekte faste kostnader materialavd. $\left(\mathrm{MO}_{\mathrm{F}}\right): 50 \%$
- Indirekte faste kostnader produksjonsavd. $\left(\mathrm{TO}_{\mathrm{F}}\right): 150 \%$
- Indirekte variable kostnader produksjonsavd. ( $\mathrm{TO}_{\mathrm{v}}$ ) : 25\%
- Indirekte faste salgs- og adm. kostnader (S\&AOF) : $20 \%$

Prognosen for faste kostnader og variable kostnader per stykk viste seg å være riktig, men det sanne salget viste seg å være

| Produkt | A | B | C | D |
| :--- | :---: | :---: | :---: | :---: |
| Salgsvolum (stykk) | 8000 | 8000 | 8000 | 8000 |

Hvilket produkt vil se den største endringen i selvkostnad hvis tilleggssatsene er basert på det faktiske salget ( $S J K_{\text {Salg }}$ ) i stedet for det prognosen ( $S J K_{\text {Prognos }}$ ), dvs. hvilket produkt har størst verdi på $\left|S J K_{\text {Salg }}-S J K_{\text {Prognos }}\right|$.

In [70]:
Salgsvolum_prognose                             = np.array([8000, 8000, 10000, 10000,])
Salgspris_krStykk                               = np.array([10000, 11000, 8000, 9000,])
Direkte_material_krStykk                        = np.array([1600, 1700, 1200, 1400,]) 
Direkte_lønn_krStykk                            = np.array([1500, 1800, 1200, 1500,])
Øvrige_direkte_tilvirkningskostnader_krStykk    = np.array([200, 100, 100, 200,])
Salgsprovisjon_krStykk                          = np.array([1000, 1100, 800, 900,])

MO_F    = Direkte_material_krStykk * 0.5
TO_F    = Direkte_lønn_krStykk * 1.5
TO_V    = Direkte_lønn_krStykk * 0.25

kostnader_prognose = np.vstack((
    # Materialavd.
    Direkte_material_krStykk,
    MO_F,

    # Porduksjonsavd.
    Direkte_lønn_krStykk,
    TO_V,
    TO_F,
    
    ## 
    Øvrige_direkte_tilvirkningskostnader_krStykk,
))
display(kostnader_prognose)
TK_prognose = np.sum(kostnader_prognose, axis=0)

SAO_F_prognose = 0.2*TK_prognose.sum()*TK_prognose/TK_prognose.sum()

SJK_prognose = np.vstack((
    TK_prognose,
    SAO_F_prognose,
    Salgsprovisjon_krStykk,
))

display(SJK_prognose)
display(np.sum(SJK_prognose,axis=0))

Salgsvolum_salg = np.array([8000, 8000, 8000, 8000,])

# MO_F_salg
MO_F_total = (Salgsvolum_prognose * MO_F).sum()
Direkte_material_total = (Direkte_material_krStykk * Salgsvolum_salg).sum()
MO_F_salg = Direkte_material_krStykk * MO_F_total/Direkte_material_total 
display(MO_F_salg)

# TO_F_salg
TO_F_total = (Salgsvolum_prognose * TO_F).sum()
Direkte_lønn_total = (Direkte_lønn_krStykk * Salgsvolum_salg).sum()
TO_F_salg = Direkte_lønn_krStykk * TO_F_total/Direkte_lønn_total 
display(TO_F_salg)

kostnader_salg = np.vstack((
    # Materialavd.
    Direkte_material_krStykk,
    MO_F_salg,

    # Porduksjonsavd.
    Direkte_lønn_krStykk,
    TO_V,
    TO_F_salg,
    
    ## 
    Øvrige_direkte_tilvirkningskostnader_krStykk,
))
display(kostnader_salg)
TK_salg = np.sum(kostnader_salg, axis=0)

# TO_F_salg
SAO_F_total = (Salgsvolum_prognose * SAO_F_prognose).sum()
TK_total = (TK_salg * Salgsvolum_salg).sum()
SAO_F_andel = SAO_F_total/TK_total 
display(SAO_F_andel)
SAO_F_salg = SAO_F_andel*TK_salg.sum()*TK_salg/TK_salg.sum()

SJK_salg = np.vstack((
    TK_salg,
    SAO_F_salg,
    Salgsprovisjon_krStykk,
))

display(SJK_salg)
display(np.sum(SJK_salg,axis=0))

display(np.sum(SJK_salg,axis=0)-np.sum(SJK_prognose,axis=0))

array([[1600., 1700., 1200., 1400.],
       [ 800.,  850.,  600.,  700.],
       [1500., 1800., 1200., 1500.],
       [ 375.,  450.,  300.,  375.],
       [2250., 2700., 1800., 2250.],
       [ 200.,  100.,  100.,  200.]])

array([[6725., 7600., 5200., 6425.],
       [1345., 1520., 1040., 1285.],
       [1000., 1100.,  800.,  900.]])

array([ 9070., 10220.,  7040.,  8610.])

array([888.13559322, 943.6440678 , 666.10169492, 777.11864407])

array([2503.125, 3003.75 , 2002.5  , 2503.125])

array([[1600.        , 1700.        , 1200.        , 1400.        ],
       [ 888.13559322,  943.6440678 ,  666.10169492,  777.11864407],
       [1500.        , 1800.        , 1200.        , 1500.        ],
       [ 375.        ,  450.        ,  300.        ,  375.        ],
       [2503.125     , 3003.75      , 2002.5       , 2503.125     ],
       [ 200.        ,  100.        ,  100.        ,  200.        ]])

0.2114979386165827

array([[7066.26059322, 7997.3940678 , 5468.60169492, 6755.24364407],
       [1494.49954919, 1691.43235964, 1156.59798559, 1428.72010557],
       [1000.        , 1100.        ,  800.        ,  900.        ]])

array([ 9560.76014241, 10788.82642744,  7425.1996805 ,  9083.96374964])

array([490.76014241, 568.82642744, 385.1996805 , 473.96374964])

## Oppgave 5

Hvis de faste kostnadene er 100000 kroner og den variable kostnaden kan uttrykkes som $\mathrm{VC}(\mathrm{Q})=5 \mathrm{Q}$ kroner der $\mathrm{Q}$ er mengden.

Hvilken pris per enhet (i kroner) må man da sette for å få en sikkerhetsmargin på $10 \%$ ved mengden 10000 ?

---

$Q_{min} = (1 - sikkerhetsmargin) \times Q_{mengde}$

$TP(Q) = Q_{min} \times (\text{pris} - \frac{dVC}{dQ}) - FC = 0$


In [78]:
Q, p = sp.symbols('Q p')

FC = 100000
VC = 5*Q

Q_mengde = 10000
Q_min = (1-0.1)*Q_mengde

TP = Q_min * (p - VC.diff(Q)) - FC
pris = sp.solve(TP)[0]
print(pris)

16.1111111111111


## Oppgave 6

En bedrift har totalkapitalrentabilitet før skatt på 15\%. Renten på gjeld er 4.5\% og gjeldsgraden er $70 \%$.

Hva blir bedriftens egenkapitalrentabilitet før skatt?

In [79]:
totalkapitalrentabilitet = 0.15
gjeldsrente = 0.045
gjeldsgraden = 0.7

egenkapitalrentabilitet = totalkapitalrentabilitet + (totalkapitalrentabilitet-gjeldsrente) * gjeldsgraden
print(egenkapitalrentabilitet)

0.22349999999999998


## Oppgave 7

Hvis nåverdien av en betaling på 2000 kroner om fire år er 1600 kroner og inflasjonen er 4\%, hva er da den nominelle kalkulasjonsrenten?

In [86]:
r = sp.symbols('r')
Eq7 = 1600 - 2000/(1+r)**4
solutions_7 = sp.solve(Eq7)

for solution in solutions_7:
    print(solution.evalf())
display(solutions_7[0].evalf())

0.0573712634405641
-1.0 - 1.05737126344056*I
-1.0 + 1.05737126344056*I
-2.05737126344056


0.0573712634405641

## Oppgave 8

En investering på 1000 nå vil gi en positiv kontantstrøm på 205 per år fra og med år 2 til og med år 10.

Hva er da internrenten?

In [116]:
C = 205
r = sp.symbols('r')
n = 10
invest = 1000

PV = C * (1 - (1 + r)**(-(n)))/r
NNV_y1 = (C/(1+r)**1)
NNV = PV - NNV_y1 - invest

IRR = sp.solve(NNV, r)  # Starting with an initial guess of 10% (0.1)
for solution in IRR:
    print(solution.evalf())

print(f"{IRR[1].evalf():.3f}")

-1.81607045065307
0.114691153214904
-1.67733408272876 - 0.453430295838084*I
-1.67733408272876 + 0.453430295838084*I
-1.30475414821111 - 0.757069100023018*I
-1.30475414821111 + 0.757069100023018*I
-0.814278028972359 - 0.806379920687221*I
-0.814278028972359 + 0.806379920687221*I
-0.352944091368683 - 0.570160496488773*I
-0.352944091368683 + 0.570160496488773*I
0.115
