In [19]:
import numpy as np
import sympy as sp


num_a = ( 0.1 / 0.09 ) - 1
num_b = 0.25 * 1
num_c = 1.4 * 10
num_d = 1.0 * 1

# metall = np.array([P1, P2, P3])
metall = np.array([0.1+num_d, -0.1*2, -num_d])
strøm = np.array([-1, (1+num_a)*2, -num_a])
dingsar = np.array([0, 0, 1])

P = np.array(['P1', 'P2', 'P3'])

A = (np.vstack((
    #P,
    metall,
    strøm,
    dingsar
)))

display(A)

array([[ 1.1       , -0.2       , -1.        ],
       [-1.        ,  2.22222222, -0.11111111],
       [ 0.        ,  0.        ,  1.        ]])

In [20]:
metallmalm = np.array([-10, 0, 0])
CO_2 = np.array([num_c, 0.5*2, num_b])

B = np.vstack((
    metallmalm,
    CO_2
))
display(B)

array([[-10.  ,   0.  ,   0.  ],
       [ 14.  ,   1.  ,   0.25]])

In [21]:

# metall = np.array([P1, P2, P3])
r_metall = np.array([0])
r_strøm = np.array([0])
r_dingsar = np.array([1])

r = (np.vstack((
    r_metall,
    r_strøm,
    r_dingsar
)))
display(r)
r = np.array([0, 0, 1])
display(r)

array([[0],
       [0],
       [1]])

array([0, 0, 1])

In [22]:
x = np.linalg.solve(A,r)
display(x)

array([1. , 0.5, 1. ])

In [23]:
display(np.sum(x*B,axis=1))


array([-10.  ,  14.75])

In [ ]:

c02_dingsar = np.sum(x*B.T, axis=0)[1]
display(c02_dingsar)