# Oppgave 1

In [13]:
import numpy as np
import sympy as sp

##strøm = np.array([P1, P2, P3])
#strøm = np.array([P1, P2, P3])
#stål = np.array([P1, P2, P3])
#strøm = np.array([P1, P2, P3])

n_21 = 3000
n_1 = 98000
n_12 = 98000
n_2 = 140000
n_13 = 14000
n_23 = 140000

# INN: NEGATIV -> UT: POSITIV
#P1= np.array([strøm, stål, vindmøller])
P1 = np.array([n_1, -n_21, 0])
P2 = np.array([-n_12, n_2, 0])
P3 = np.array([-n_13, -n_23, 25])

A = np.vstack((
    P1,
    P2*2,
    P3,
)).T
display(A)

w_1 = 14700
q_1 = 93
p_1 = 4900
w_2 = 0
q_2 = 225
p_2 = 13400
w_3 = 2800
q_3 = 285
p_3= 15000

#B1= np.array(['vann', 'NO_x', 'CO_2'])
B1 = np.array([-w_1, q_1, p_1])
B2 = np.array([-w_2, q_2, p_2])
B3 = np.array([-w_3, q_3, p_3])

B = np.vstack((
    B1,
    B2*2,
    B3
)).T

display(B)

r = np.array([0, 0, 1])

x = np.linalg.solve(A,r)

display(x)

display(x*B)
ressursuttak_gitt_r = np.sum(x*B, axis=1)
display(ressursuttak_gitt_r)
nox_vindmolle = ressursuttak_gitt_r[1]
display(nox_vindmolle)

array([[  98000, -196000,  -14000],
       [  -3000,  280000, -140000],
       [      0,       0,      25]])

array([[-14700,      0,  -2800],
       [    93,    450,    285],
       [  4900,  26800,  15000]])

array([0.04671533, 0.02050052, 0.04      ])

array([[-686.71532847,    0.        , -112.        ],
       [   4.34452555,    9.22523462,   11.4       ],
       [ 228.90510949,  549.41397289,  600.        ]])

array([-798.71532847,   24.96976017, 1378.31908238])

24.96976016684046

# Oppgave 2

In [12]:
# P= np.array([x01, x12, x13, x31, x20, x23, x03])
P1 = np.array([1, -1, -1, 1, 0, 0, 0])
P2 = np.array([0, 1, 0, 0, -1, -1, 0])
P3 = np.array([0, 0, 1, -1, 0, 1, 1])

# M= np.array([x01, x12, x13, x31, x20, x23, x03])
M1 = np.array([-0.81, 1, 0, -0.81, 0, 0, 0])
M2 = np.array([0, 0, -0.5, 1, 0, -0.5, -0.5])

m_ny = (68 * 29)/0.81*0.5
M3 = np.array([1, 0, 0, 0, 0, 0, 0])

A_bal = np.vstack((
    P1,
    P2,
    P3
))
display(A_bal)

array([[ 1, -1, -1,  1,  0,  0,  0],
       [ 0,  1,  0,  0, -1, -1,  0],
       [ 0,  0,  1, -1,  0,  1,  1]])